#pragma once

#include <array>
#include <cstdint>
#include <vector>
#include "lut.hpp"

namespace cubelut {

enum class Interpolation {
    Trilinear,
    Tetrahedral
};

class Processor {
public:
    // Apply LUT to a single pixel (RGB in range [0, 1])
    static std::array<float, 3> process(const Lut& lut, const std::array<float, 3>& pixel, Interpolation interp = Interpolation::Tetrahedral);

    // Apply LUT to a specified chunk of an image in-place (RGB format, floats)
    // startIndex and endIndex are in PIXEL count (not float count).
    // E.g., for the whole image, use 0 and width * height.
    static void processPixels(const Lut& lut, float* data, size_t startIndex, size_t endIndex, Interpolation interp = Interpolation::Tetrahedral);

    // Apply LUT to an entire image in-place (RGB format, floats). Helper wrapper.
    static void processImage(const Lut& lut, float* data, size_t width, size_t height, Interpolation interp = Interpolation::Tetrahedral) {
        processPixels(lut, data, 0, width * height, interp);
    }

    // ------------------------------------------------------------------
    // Parallel processing
    // ------------------------------------------------------------------

    /// Descriptor for one SIMD/cache-aligned pixel range.
    /// Generated by getParallelChunks() for use with any thread pool.
    struct PixelChunk {
        size_t startPixel; ///< Inclusive start (always a multiple of 16).
        size_t endPixel;   ///< Exclusive end.
    };

    /// Compute cache-line and SIMD-aligned pixel chunks for parallel dispatch.
    ///
    /// Alignment: every startPixel is a multiple of 16 pixels (= 192 bytes),
    /// satisfying both AVX-512 lane alignment AND cache-line false-sharing safety
    /// (LCM(64-byte cache line, 12-byte RGB pixel) = 192 bytes = 16 pixels).
    ///
    /// Typical usage with any thread pool:
    ///
    ///   // With GCD (Swift / Objective-C)
    ///   auto chunks = Processor::getParallelChunks(W, H, 0);
    ///   dispatch_apply(chunks.size(), queue, ^(size_t i) {
    ///       Processor::processPixels(lut, data, chunks[i].startPixel, chunks[i].endPixel);
    ///   });
    ///
    ///   // With TBB
    ///   tbb::parallel_for(tbb::blocked_range<size_t>(0, chunks.size()), [&](auto& r) {
    ///       for (size_t i = r.begin(); i < r.end(); ++i)
    ///           Processor::processPixels(lut, data, chunks[i].startPixel, chunks[i].endPixel);
    ///   });
    static std::vector<PixelChunk> getParallelChunks(
        size_t width,
        size_t height,
        unsigned numThreads = 0  // 0 = std::thread::hardware_concurrency()
    );

    /// Parallel image processing with platform-adaptive dispatch:
    ///   - Apple platforms: uses dispatch_apply() (GCD pre-warmed pool, ~1 µs overhead)
    ///   - Other platforms: uses std::async(launch::async)  (~120 µs overhead)
    ///
    /// For real-time / video pipelines on Apple, prefer this over processImage().
    /// For custom thread pools (game engines, servers), use getParallelChunks() instead.
    ///
    /// numThreads: 0 = platform default (hardware_concurrency)
    static void processImageParallel(
        const Lut& lut,
        float* data,
        size_t width,
        size_t height,
        Interpolation interp = Interpolation::Tetrahedral,
        unsigned numThreads  = 0
    );

    // ------------------------------------------------------------------
    // uint8 image processing (RGB8 = 3 bytes/pixel, RGBA8 = 4 bytes/pixel)
    // ------------------------------------------------------------------

    /// Apply LUT to a uint8 RGB image (3 bytes/pixel).
    /// Internally: converts 4096-pixel chunks float32 (L2-hot), processes via
    /// existing SIMD path, converts back with round-to-nearest quantization.
    /// input == output is safe (block-by-block processing avoids overlap).
    static void processImageU8(
        const Lut&     lut,
        const uint8_t* input,
        uint8_t*       output,
        size_t         width,
        size_t         height,
        Interpolation  interp = Interpolation::Tetrahedral
    );

    /// Parallel uint8 RGB processing (platform-adaptive: GCD / std::async).
    static void processImageU8Parallel(
        const Lut&     lut,
        const uint8_t* input,
        uint8_t*       output,
        size_t         width,
        size_t         height,
        Interpolation  interp      = Interpolation::Tetrahedral,
        unsigned       numThreads  = 0
    );

    /// Apply LUT to a uint8 RGBA image (4 bytes/pixel).
    /// Alpha channel is read unchanged (passthrough). RGBA8 is cache-line
    /// friendly: 16 pixels per cache line (same as float32 RGB).
    static void processImageRGBA8(
        const Lut&     lut,
        const uint8_t* input,
        uint8_t*       output,
        size_t         width,
        size_t         height,
        Interpolation  interp = Interpolation::Tetrahedral
    );

    /// Parallel uint8 RGBA processing.
    static void processImageRGBA8Parallel(
        const Lut&     lut,
        const uint8_t* input,
        uint8_t*       output,
        size_t         width,
        size_t         height,
        Interpolation  interp      = Interpolation::Tetrahedral,
        unsigned       numThreads  = 0
    );

    // SIMD-accelerated RGB float32 → RGBA float32 packing (alpha channel = 1.0f).
    // `rgba` must point to a buffer of at least numPixels * 4 floats.
    static void convertRGBToRGBA32(const float* rgb, float* rgba, size_t numPixels);

    // SIMD-accelerated RGB float32 → RGBA float16 packing (alpha = 0x3C00 = 1.0f in IEEE 754 half).
    // `rgba16` must point to a buffer of at least numPixels * 4 uint16_t values.
    static void convertRGBToRGBA16(const float* rgb, uint16_t* rgba16, size_t numPixels);

private:
    static std::array<float, 3> process1D(const LutData1D& lut, const std::array<float, 3>& pixel);
    static std::array<float, 3> process3DTrilinear(const LutData3D& lut, const std::array<float, 3>& pixel);
    static std::array<float, 3> process3DTetrahedral(const LutData3D& lut, const std::array<float, 3>& pixel);
};

} // namespace cubelut
